import "server-only";

import type { StyleJson } from "@/lib/subtitles/themes";

/**
 * ASS (Advanced SubStation Alpha) subtitle writer for libass.
 *
 * Each clip's words become karaoke-highlighted events. We surface the active
 * word by recoloring it to the theme's highlight color via `\k` timing tags,
 * while the rest of the line stays the primary color — the classic
 * TikTok/Hormozi per-word pop.
 *
 * All times are CLIP-RELATIVE (0-based) so the burn-in filter and the trimmed
 * source share the same timeline (the subtitles filter is applied after trim).
 */

export type AssWord = {
  text: string;
  startMs: number;
  endMs: number;
};

export type AssLine = {
  /** Clip-relative start, ms. */
  startMs: number;
  /** Clip-relative end, ms. */
  endMs: number;
  words: AssWord[];
};

/** HSL [h(0-360), s(0-1), l(0-1)] -> ASS &HAABBGGRR (AA=00 opaque). */
export function hslToAssColor(hsl: [number, number, number]): string {
  const [h, s, l] = hsl;
  const c = (1 - Math.abs(2 * l - 1)) * s;
  const hp = h / 60;
  const x = c * (1 - Math.abs((hp % 2) - 1));
  let r1 = 0,
    g1 = 0,
    b1 = 0;
  if (hp >= 0 && hp < 1) [r1, g1, b1] = [c, x, 0];
  else if (hp < 2) [r1, g1, b1] = [x, c, 0];
  else if (hp < 3) [r1, g1, b1] = [0, c, x];
  else if (hp < 4) [r1, g1, b1] = [0, x, c];
  else if (hp < 5) [r1, g1, b1] = [x, 0, c];
  else if (hp < 6) [r1, g1, b1] = [c, 0, x];
  const m = l - c / 2;
  const r = Math.round((r1 + m) * 255);
  const g = Math.round((g1 + m) * 255);
  const b = Math.round((b1 + m) * 255);
  // ASS stores BGR with alpha as ABGR hex; alpha 00 = opaque (libass convention).
  const toHex = (n: number) => n.toString(16).padStart(2, "0");
  return `&H00${toHex(b)}${toHex(g)}${toHex(r)}`.toUpperCase();
}

function formatAssTime(ms: number): string {
  // libass uses H:MM:SS.cs (centiseconds).
  const csTotal = Math.max(0, Math.round(ms / 10));
  const cs = csTotal % 100;
  const sTotal = Math.floor(csTotal / 100);
  const s = sTotal % 60;
  const mTotal = Math.floor(sTotal / 60);
  const m = mTotal % 60;
  const h = Math.floor(mTotal / 60);
  const pad = (n: number, w = 2) => n.toString().padStart(w, "0");
  return `${h}:${pad(m)}:${pad(s)}.${pad(cs)}`;
}

/** Escape text for ASS dialogue (commas are field separators, so replace them). */
function esc(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/\{|\}/g, "").replace(/\n/g, "\\N");
}

/**
 * Build a full `.ass` document for the given (clip-relative) lines.
 * `style` drives the `[V4+ Styles]` line + per-event override blocks.
 */
export function buildAss(lines: AssLine[], style: StyleJson): string {
  const primary = hslToAssColor(style.primaryHsl);
  const outline = hslToAssColor(style.outlineHsl);
  const highlight = hslToAssColor(style.highlightHsl);

  const header = [
    "[Script Info]",
    "; Generated by AI Shorts Studio",
    "ScriptType: v4.00+",
    "PlayResX: 1080",
    "PlayResY: 1920",
    "WrapStyle: 2",
    "ScaledBorderAndShadow: yes",
    "",
    "[V4+ Styles]",
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
    `Style: Default,${style.font},${style.fontSize},${primary},${primary},${outline},${outline},${style.bold},0,0,0,100,100,0,0,1,${style.outline},${style.shadow},${style.alignment},${style.marginL},${style.marginL},${style.marginV},1`,
    "",
    "[Events]",
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
  ];

  const body = lines.map((line) => {
    // Per-word karaoke: a single Dialogue line whose words each carry a \k
    // duration (centiseconds). The active word is recolored to the highlight;
    // the rest stay primary. libass advances the karaoke highlight across the
    // durations, giving the TikTok/Hormozi per-word pop.
    const parts: string[] = [];
    for (const w of line.words) {
      const durCs = Math.max(1, Math.round((w.endMs - w.startMs) / 10));
      const word = esc(w.text);
      // \k<dur> then set the word's fill to highlight, then restore primary for
      // subsequent words. The trailing space keeps spacing natural.
      parts.push(`{\\k${durCs}}{\\1c${highlight}}${word}{\\1c${primary}} `);
    }
    const text = parts.join("");
    return `Dialogue: 0,${formatAssTime(line.startMs)},${formatAssTime(line.endMs)},Default,,0,0,0,,${text}`;
  });

  return [...header, ...body, ""].join("\r\n");
}
